### Exercice 1:
Create a 1-dimensional NumPy array with 5 integers from 0 to 4.

In [2]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

 ### Exercice 2:
 Create a 2-dimensional NumPy array with shape (2, 3) containing only ones.

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Exercice 3:
Create a 3-dimensional NumPy array with shape (2, 3, 4) containing only zeros.

In [8]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Exercice 4:
Create a 2-dimensional NumPy array with shape (3, 4) containing random integers between 0 and 9.

In [13]:
arr = np.random.randint(0,9,(3,4))

### Exercice 5:
Create a 2-dimensional NumPy array with shape (3, 4) and find its dimensions and size.

In [16]:
arr.ndim, arr.shape, arr.size

(2, (3, 4), 12)

### Exercice 6:
Create a 2-dimensional NumPy array with shape (3, 4) and calculate the sum of all its elements.

In [19]:
arr.sum(), np.sum(arr)

(33, 33)

In [18]:
arr

array([[2, 2, 0, 0],
       [3, 4, 5, 7],
       [1, 7, 1, 1]])

### Exercice 7:
Create a 2-dimensional NumPy array with shape (3, 4) and find the minimum and maximum value in each row.

In [24]:
maxi =[]
mini = []
d = {'maxi': [],'mini':[]}
for i in arr :
  d['maxi'].append(i.max())
  d['mini'].append(i.min())

print(d)

{'maxi': [2, 7, 7], 'mini': [0, 3, 1]}


### Exercice 8:
Create a 2-dimensional NumPy array with shape (3, 4) and replace all the odd numbers with -1.

In [25]:
arr = np.random.randint(1000,3000,(3,4))

In [26]:
arr

array([[2642, 2336, 2727, 2253],
       [1414, 1927, 2931, 1492],
       [2682, 1551, 1263, 2814]])

In [27]:
arr[arr%2 != 0] =-1

In [28]:
arr

array([[2642, 2336,   -1,   -1],
       [1414,   -1,   -1, 1492],
       [2682,   -1,   -1, 2814]])

### Exercice 9:
Create a 2-dimensional NumPy array with shape (3, 4) and extract the elements in the second and third row and the second and third column.

In [30]:
arr = np.random.randint(1000,3000,(3,4))
arr

array([[2524, 2517, 2613, 2718],
       [1397, 1168, 2675, 1008],
       [1536, 1365, 2549, 1774]])

In [32]:
arr[1:3, 1:3]

array([[1168, 2675],
       [1365, 2549]])

### Exercice 10:
Create a 2-dimensional NumPy array with shape (3, 4) and multiply each element by 2.

In [35]:
arr = np.random.randint(1,5,(3,4))
arr*2

array([[2, 8, 2, 8],
       [4, 6, 8, 6],
       [8, 2, 8, 4]])

In [36]:
arr

array([[1, 4, 1, 4],
       [2, 3, 4, 3],
       [4, 1, 4, 2]])